server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/postulant/**
            - Path=/company/**
            - Path=/employer/**
            - Path=/language/**
            - Path=/sector/**
            - Path=/skill/**
            - Path=/study/**
        - id: postulation-service
          uri: lb://postulation-service
          predicates:
            - Path=/postulation/**
        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/subscription/**
        - id: joboffer-service
          uri: lb://joboffer-service
          predicates:
            - Path=/joboffer/**
            - Path=/contract/**
            - Path=/interview/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/invoice/**,/payment/**



