server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        routes:
          - id: user-service
            uri: lb://user-microservice
            predicates:
              - Path=/postulant/**
              - Path=/company/**
              - Path=/cv/**
              - Path=/employer/**
              - Path=/language/**
              - Path=/sector/**
              - Path=/skill/**
              - Path=/study/**
          - id: joboffer-service
            uri: lb://joboffer-service
            predicates:
              - Path=/joboffers/**
          - id: subscription-service
            uri: lb://subscription-microservice
            predicates:
              - Path=/subscription/**
          - id: postulation-service
            uri: lb://postulation-service
            predicates:
              - Path=/postulation/**
          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/payments/**

