server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-microservice
          uri: lb://user-service
          predicates:
            - Path=/postulant/**
            - Path=/company/**
            - Path=/employer/**
            - Path=/language/**
            - Path=/sector/**
            - Path=/skill/**
            - Path=/study/**
        - id: postulation-service
          uri: lb://postulation-service
          predicates:
            - Path=/postulation/**
        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/subscription/**



